syntax = "proto3";

package tunnel;

import "google/api/annotations.proto";

option go_package = "github.com/Dyastin-0/wormhole/api/proto/tunnel;tunnel";

service TunnelService {
  rpc GetTunnel(GetTunnelRequest) returns (Tunnel) {
    option (google.api.http) = {
      get: "/tunnels/{id}"
    };
  }

  rpc CreateTunnel(CreateTunnelRequest) returns (Tunnel) {
    option (google.api.http) = {
      post: "/tunnels"
      body: "*"
    };
  }
  
  rpc UpdateTunnel(UpdateTunnelRequest) returns (Tunnel) {
    option (google.api.http) = {
      put: "/tunnels/{id}"
      body: "*"
    };
  }

  rpc DeleteTunnel(DeleteTunnelRequest) returns (Tunnel) {
    option (google.api.http) = {
      delete: "/tunnels/{id}"
    }; 
  }

  rpc GetTunnels(GetTunnelsRequest) returns (GetTunnelsResponse) {
    option (google.api.http) = {
      get: "/tunnels"
    };
  }
}

message Tunnel {
  string id = 1;
  string user_id = 2;
  string name = 3;
  string domain = 4;
  string target = 5;
  string protocol = 6; 
  string ipv4 = 7;
  string created_at = 8;
  string updated_at = 9;
}

message CreateTunnelRequest {
  string user_id = 1;
  string name = 2;
  string domain = 3;
  string target = 4;
  string protocol = 5;
  string ipv4 = 6;
}

message GetTunnelRequest {
  string id = 1;
  string user_id =2;
}

message UpdateTunnelRequest {
  string id = 1;
  string name = 2;
  string domain = 3;
  string target = 4;
  string protocol = 5;
  string ipv4 = 6;
}

message DeleteTunnelRequest {
  string id = 1;
  string user_id = 2;
}

message GetTunnelsRequest {
  string user_id = 1;
  int64 page = 2;
  int64 limit = 3;
}

message GetTunnelsResponse {
  repeated Tunnel tunnels = 1;
  int64 total = 2;
  int64 page = 3;
  int64 limit = 4;
  bool has_next = 5;
}
