// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into refresh_tokens (
  id,
  user_id
) values (?, ?)
`

type CreateRefreshTokenParams struct {
	ID     string
	UserID string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.ID, arg.UserID)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
delete from refresh_tokens
where id = ? and user_id = ?
`

type DeleteRefreshTokenParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, arg.ID, arg.UserID)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
delete from refresh_tokens
where user_id = ?
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
select id, user_id
from refresh_tokens
where id = ? and user_id = ?
`

type GetRefreshTokenParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, arg.ID, arg.UserID)
	var i RefreshToken
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}
