// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type RefreshToken struct {
	ID     string
	UserID string
}

type Tunnel struct {
	ID        string
	UserID    string
	Name      string
	Domain    string
	Target    string
	Protocol  string
	Ipv4      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        string
	Email     string
	Username  string
	Name      string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
