// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tunnel.sql

package db

import (
	"context"
	"database/sql"
)

const createTunnel = `-- name: CreateTunnel :one
insert into tunnels (name, domain, target, protocol, ipv4, id, user_id, updated_at)
values (?, ?, ?, ?, ?, ?, ?, ?)
returning id, user_id, name, domain, target, protocol, ipv4, created_at, updated_at
`

type CreateTunnelParams struct {
	Name      string
	Domain    string
	Target    string
	Protocol  string
	Ipv4      string
	ID        string
	UserID    string
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateTunnel(ctx context.Context, arg CreateTunnelParams) (Tunnel, error) {
	row := q.db.QueryRowContext(ctx, createTunnel,
		arg.Name,
		arg.Domain,
		arg.Target,
		arg.Protocol,
		arg.Ipv4,
		arg.ID,
		arg.UserID,
		arg.UpdatedAt,
	)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.Target,
		&i.Protocol,
		&i.Ipv4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTunnel = `-- name: DeleteTunnel :one
delete from tunnels
where id = ? and user_id = ?
returning id, user_id, name, domain, target, protocol, ipv4, created_at, updated_at
`

type DeleteTunnelParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTunnel(ctx context.Context, arg DeleteTunnelParams) (Tunnel, error) {
	row := q.db.QueryRowContext(ctx, deleteTunnel, arg.ID, arg.UserID)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.Target,
		&i.Protocol,
		&i.Ipv4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTunnel = `-- name: GetTunnel :one
select id, user_id, name, domain, target, protocol, ipv4, created_at, updated_at
from tunnels
where user_id = ? and id = ?
`

type GetTunnelParams struct {
	UserID string
	ID     string
}

func (q *Queries) GetTunnel(ctx context.Context, arg GetTunnelParams) (Tunnel, error) {
	row := q.db.QueryRowContext(ctx, getTunnel, arg.UserID, arg.ID)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.Target,
		&i.Protocol,
		&i.Ipv4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTunnels = `-- name: GetTunnels :many
select id, user_id, name, domain, target, protocol, ipv4, created_at, updated_at
from tunnels
where user_id = ?
order by domain
`

func (q *Queries) GetTunnels(ctx context.Context, userID string) ([]Tunnel, error) {
	rows, err := q.db.QueryContext(ctx, getTunnels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tunnel
	for rows.Next() {
		var i Tunnel
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Domain,
			&i.Target,
			&i.Protocol,
			&i.Ipv4,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTunnel = `-- name: UpdateTunnel :one
update tunnels
set 
  name = COALESCE(?2, name),
  domain = COALESCE(?3, domain), 
  target = COALESCE(?4, target), 
  protocol = COALESCE(?5, protocol),
  ipv4 = COALESCE(?6, ipv4),
  updated_at = current_timestamp
where id = ?
returning id, user_id, name, domain, target, protocol, ipv4, created_at, updated_at
`

type UpdateTunnelParams struct {
	Name     sql.NullString
	Domain   sql.NullString
	Target   sql.NullString
	Protocol sql.NullString
	Ipv4     sql.NullString
	ID       string
}

func (q *Queries) UpdateTunnel(ctx context.Context, arg UpdateTunnelParams) (Tunnel, error) {
	row := q.db.QueryRowContext(ctx, updateTunnel,
		arg.Name,
		arg.Domain,
		arg.Target,
		arg.Protocol,
		arg.Ipv4,
		arg.ID,
	)
	var i Tunnel
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.Target,
		&i.Protocol,
		&i.Ipv4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
