
syntax = "proto3";

package user;

import "google/api/annotations.proto";

option go_package = "github.com/Dyastin-0/wormhole/api/proto/user;user";

service UserService {
  rpc GetUser(GetUserRequest) returns (User) {
    option (google.api.http) = {
      get: "/users/{email}"
    };
  }

  rpc CreateUser(CreateUserRequest) returns (User) {
    option (google.api.http) = {
      post: "/users"
      body: "*"
    };
  }

  rpc UpdateUser(UpdateUserRequest) returns (User) {
    option (google.api.http) = {
      put: "/users/{id}"
      body: "*"
    };
  }

  rpc DeleteUser(DeleteUserRequest) returns (User) {
    option (google.api.http) = {
      delete: "/users/{id}"
    };
  }

  rpc GetUsers(GetUsersRequest) returns (GetUsersResponse) {
    option (google.api.http) = {
      get: "/users"
    };
  }
}


message User {
  string id = 1;
  string email = 2;
  string username = 3;
  string name = 4;
}

message GetUserRequest {
  string email = 1;
}

message CreateUserRequest {
  string email = 1;
  string username = 2;
  string name = 3;
  string password = 4;
}

message UpdateUserRequest {
  string id = 1;
  string email = 2;
  string username = 3;
  string name = 4;
  string password = 5;
}

message DeleteUserRequest {
  string id = 1;
}

message GetUsersRequest {
  int64 page = 1;   
  int64 limit = 2; 
}

message GetUsersResponse {
  repeated User users = 1;
  int64 total = 2;     
  int64 page = 3;      
  int64 limit = 4;     
  bool has_next = 5;
}
