name: Deploy

on:
  push:
    branches: [ master ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          set -e
          cd prod/wormhole
          git pull origin master
          go test ./... -v
          go install .
          sudo systemctl restart wormhole.service
